import type { Scenario } from '../types/scenario'

export const FIXED_SCENARIO: Scenario = {
  title: '黄昏の晩餐会',
  synopsis: '孤島の洋館で開催された晩餐会。翌朝、資産家の黒崎源一郎が書斎で冷たくなって発見された。毒殺と思われる。招待された6名の中に犯人がいる。',
  setting: '孤島に建つゴシック様式の洋館。外は嵐で孤立無援の状況。',
  victim: {
    name: '黒崎源一郎',
    appearance_id: 'male_elderly',
    description: '70代の資産家。鋭い目つきと白い顎髭が特徴。強引な性格で多くの人に恨まれていた。',
    cause_of_death: '致死量のアコニチン（トリカブト毒）による中毒死',
  },
  murderer_id: 'shiraishi_makoto',
  motive: '黒崎が書き換えた遺言書を元に戻すため。自分への遺産相続分が削除されていた。',
  truth: '白石誠は黒崎の遠縁で、遺言書に多額の遺産を相続する予定だった。しかし黒崎が密かに遺言書を書き換え、白石への相続分を全て削除していた。白石は書斎の金庫に保管された遺言書の写しを見て事実を知り、晩餐会当日にワイングラスにトリカブト毒を混入した。庭園で採取した毒草を事前に精製し、キッチンで機会を伺って実行した。',
  suspects: [
    {
      id: 'shiraishi_makoto',
      name: '白石誠',
      appearance_id: 'male_young',
      age: 32,
      occupation: '無職（元投資家）',
      description: '端正な顔立ちの青年。常に落ち着いた笑みを浮かべているが、目が笑っていない。',
      personality: '計算高く冷静。感情を表に出さない。',
      alibi: '晩餐会の間はずっとダイニングにいたと主張。しかし30分の空白がある。',
      secret: '多額の借金を抱えており、遺産が唯一の頼みだった。',
      relationship_to_victim: '遠縁の甥。遺言書で多額の遺産を相続予定だった（本人はそう思っていた）。',
      investigation_dialog: {
        greeting: '…やあ、何か用かな。私はただの参加者に過ぎないよ。',
        statements: [
          '黒崎のおじさんとは長い付き合いだ。まさかこんな形で別れることになるとは思わなかった。',
          '晩餐会の間、私はずっとダイニングで皆と一緒にいた。それが私のアリバイだ。',
          '庭園？そんな夜に外へ出る理由がないじゃないか。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: '…それは私のものじゃない。誰かが嵌めようとしているんだろう。', behavior: 'evasive' },
        will_document: { reaction: 'その遺言書は…偽物だ。本物はもっと違う内容のはずだ。', behavior: 'nervous' },
        herb_fragment: { reaction: '庭の植物？私は植物学など知らない。', behavior: 'nervous' },
        wine_glass: { reaction: '…ワイングラスが何だというんだ。みんな使っていたじゃないか。', behavior: 'angry' },
        muddy_shoes: { reaction: '泥…？これは関係ない。庭には誰でも出られる。', behavior: 'evasive' },
        note_paper: { reaction: 'そのメモは私には関係ない。', behavior: 'calm' },
        torn_letter: { reaction: 'その手紙は見たことがない。', behavior: 'calm' },
        kitchen_knife: { reaction: 'これは普通の包丁だろう。料理人なら誰でも使う。', behavior: 'calm' },
        photo_garden: { reaction: '写真？何が写っているんだ。', behavior: 'nervous' },
        safe_key: { reaction: '金庫の鍵…それがどうしたんだ。', behavior: 'angry' },
        handkerchief: { reaction: 'ハンカチか。私のものじゃない。', behavior: 'calm' },
        diary_entry: { reaction: '日記に何が書いてある…？', behavior: 'nervous' },
      },
    },
    {
      id: 'kurosaki_misaki',
      name: '黒崎美咲',
      appearance_id: 'female_young',
      age: 28,
      occupation: 'OL',
      description: '被害者の姪。黒い喪服のような服が印象的。泣き腫らした目をしている。',
      personality: '感情的で思ったことをすぐ口にする。',
      alibi: '自室で眠っていたと主張。',
      secret: '黒崎に多額の借金があり、返済を迫られていた。',
      relationship_to_victim: '姪。かつては溺愛されていたが、最近は関係が冷え込んでいた。',
      investigation_dialog: {
        greeting: 'あなたも調べているの？叔父の死の真相を…私も知りたい。',
        statements: [
          '叔父はお金に厳しくて、私への返済期限が来週だったの。でもだからって殺したりしない。',
          '昨晩は早めに部屋に引き取ったわ。あの晩餐会の雰囲気が嫌で。',
          '白石さんが怪しいと思う。叔父の遺言のことで揉めていたって聞いたもの。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: 'これは…毒？こんなものが館に！？', behavior: 'sad' },
        will_document: { reaction: '遺言書！これって叔父の…内容が違う。書き換えられてる！', behavior: 'angry' },
        herb_fragment: { reaction: 'これって…トリカブトの葉じゃないの？庭にあったの？', behavior: 'nervous' },
        wine_glass: { reaction: 'ワイングラスに毒が？信じられない…誰がこんな事を。', behavior: 'sad' },
        muddy_shoes: { reaction: '泥のついた靴？昨晩誰かが外に出たのね。', behavior: 'calm' },
        note_paper: { reaction: 'このメモの字…見覚えがある気がする。', behavior: 'nervous' },
        torn_letter: { reaction: '破られた手紙。誰かが証拠を隠滅しようとした？', behavior: 'calm' },
        kitchen_knife: { reaction: '包丁…でも叔父は毒で亡くなったんでしょ？', behavior: 'calm' },
        photo_garden: { reaction: 'この写真、庭で何かを採取している人がいる。誰なの？', behavior: 'nervous' },
        safe_key: { reaction: '叔父の金庫の鍵！これは書斎にあったはずよ。', behavior: 'angry' },
        handkerchief: { reaction: 'このハンカチは…白石さんのイニシャルじゃない？', behavior: 'nervous' },
        diary_entry: { reaction: '叔父の日記！何が書いてあるの？', behavior: 'nervous' },
      },
    },
    {
      id: 'kito_takeo',
      name: '鬼頭武雄',
      appearance_id: 'male_middle',
      age: 52,
      occupation: '会社役員',
      description: '恰幅のいい中年男性。高価なスーツを着ており、傲慢な態度が目立つ。',
      personality: '権威的で強引。金と権力を重視する。',
      alibi: 'バーラウンジで酒を飲んでいたと主張。バーテンダーが証言。',
      secret: '黒崎と共同で行った不正取引の証拠を黒崎に握られていた。',
      relationship_to_victim: 'ビジネスパートナー。表向きは友好的だが実際は脅迫関係。',
      investigation_dialog: {
        greeting: 'なんだ、君か。私は忙しい。手短に頼む。',
        statements: [
          '黒崎とは長年の付き合いだ。彼のような人物がいなくなるのは業界にとっても損失だよ。',
          '昨晩は深夜までバーで飲んでいた。バーテンダーに確認してもらえばわかる。',
          '不正取引？そんな話は知らない。根も葉もない噂だ。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: 'こんなものを使ったのか。残忍な奴だ。', behavior: 'calm' },
        will_document: { reaction: '遺言書か。私には関係ない話だ。', behavior: 'calm' },
        herb_fragment: { reaction: '植物のことは詳しくない。', behavior: 'calm' },
        wine_glass: { reaction: 'ワイングラスで毒を？用意周到な犯人だな。', behavior: 'calm' },
        muddy_shoes: { reaction: '泥だと？私は昨晩外に出ていない。', behavior: 'calm' },
        note_paper: { reaction: 'このメモ…黒崎の筆跡だな。何が書いてある？', behavior: 'nervous' },
        torn_letter: { reaction: 'これは…まずい。私宛の手紙じゃないか。', behavior: 'nervous' },
        kitchen_knife: { reaction: '刃物か。毒殺とは関係ないだろう。', behavior: 'calm' },
        photo_garden: { reaction: 'この写真は関係ない。', behavior: 'calm' },
        safe_key: { reaction: '金庫の鍵か。中身が気になるが私には関係ない。', behavior: 'nervous' },
        handkerchief: { reaction: '私のものじゃない。', behavior: 'calm' },
        diary_entry: { reaction: '日記だと！？見せろ！…いや、関係ない。', behavior: 'angry' },
      },
    },
    {
      id: 'akai_reiko',
      name: '赤井玲子',
      appearance_id: 'female_middle',
      age: 45,
      occupation: '医師',
      description: '白衣を脱いでも医師の雰囲気が漂う女性。知的な目をしている。',
      personality: '論理的で冷静。感情より事実を重視する。',
      alibi: '読書室で本を読んでいたと主張。',
      secret: '黒崎の主治医として不適切な診断書を書いたことがある。',
      relationship_to_victim: '主治医。20年来の付き合い。',
      investigation_dialog: {
        greeting: 'あなたも真相を探っているの？医師として、死因については気になることがあって。',
        statements: [
          '死因はアコニチン中毒で間違いないわ。症状と経過からして。問題は誰が投与したか。',
          '昨晩は図書室で医学書を読んでいた。正確にはアコニチンについての文献を。…偶然よ。',
          'トリカブトは庭園に生えていたはず。私は医師として知識があるけれど、だからこそ疑われるのね。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: 'アコニチンの精製品ね。これを作るには専門知識が必要よ。', behavior: 'calm' },
        will_document: { reaction: '遺言書の内容？私には関係ないけれど、誰かが動機を持っていたのね。', behavior: 'calm' },
        herb_fragment: { reaction: 'トリカブトの葉。庭で採取したものね。これだけでは毒は作れないけれど。', behavior: 'calm' },
        wine_glass: { reaction: 'ワイングラスに混入したのね。タイミングを計る必要があったはず。', behavior: 'calm' },
        muddy_shoes: { reaction: '昨晩外に出た人がいるのね。庭でトリカブトを採取するために。', behavior: 'calm' },
        note_paper: { reaction: 'このメモ…薬物の計算式？医学的な知識がある人が書いたわね。', behavior: 'nervous' },
        torn_letter: { reaction: 'この手紙は…患者の情報が含まれているようね。', behavior: 'nervous' },
        kitchen_knife: { reaction: '毒殺とは関係ないでしょう。', behavior: 'calm' },
        photo_garden: { reaction: 'この人物…夜の庭でトリカブトを採っているのね。', behavior: 'calm' },
        safe_key: { reaction: '金庫の鍵。中に何が入っているのかしら。', behavior: 'calm' },
        handkerchief: { reaction: 'このハンカチに見覚えが…白石さんのものじゃないかしら。', behavior: 'calm' },
        diary_entry: { reaction: '黒崎の日記。読んでいいものかしら…でも真相解明には必要ね。', behavior: 'calm' },
      },
    },
    {
      id: 'todo_shinichi',
      name: '藤堂慎一',
      appearance_id: 'male_young_alt',
      age: 35,
      occupation: '弁護士',
      description: 'メガネをかけた細身の男性。常に書類を持ち歩いている印象。',
      personality: '慎重で言葉を選ぶ。法的な観点から物事を見る。',
      alibi: '自室で書類仕事をしていたと主張。',
      secret: '黒崎の遺言書作成に関わっており、書き換えを知っていた。',
      relationship_to_victim: '顧問弁護士。遺言書の作成と管理を担当。',
      investigation_dialog: {
        greeting: '調査ですか。弁護士として、法的な観点から協力できることがあれば。',
        statements: [
          '黒崎様の遺言については守秘義務があります。ただ…最近変更があったことは確かです。',
          '昨晩は自室で契約書の確認をしていました。重要な案件があって。',
          '遺言書の内容が動機に関わるとすれば、相続人の確認が必要です。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: 'こんな証拠が出てくるとは…誰かが計画的に動いていたのですね。', behavior: 'calm' },
        will_document: { reaction: 'これは…！この遺言書は先月書き換えられたものです。私が立会いました。', behavior: 'nervous' },
        herb_fragment: { reaction: '植物についての知識は私にはありません。', behavior: 'calm' },
        wine_glass: { reaction: 'ワイングラスに毒を。タイミングを知っている人間の犯行ですね。', behavior: 'calm' },
        muddy_shoes: { reaction: '外に出た人物がいるのですね。記録しておきます。', behavior: 'calm' },
        note_paper: { reaction: 'このメモは…法的に見て問題のある内容が含まれています。', behavior: 'nervous' },
        torn_letter: { reaction: 'この手紙…黒崎様から私への連絡ですね。証拠として保全が必要です。', behavior: 'nervous' },
        kitchen_knife: { reaction: '今回の件には関係ないと思われます。', behavior: 'calm' },
        photo_garden: { reaction: 'この写真の人物…白石さんに似ていますね。', behavior: 'nervous' },
        safe_key: { reaction: '金庫の鍵！これは書斎の金庫に保管されているはずの…なぜここに？', behavior: 'angry' },
        handkerchief: { reaction: '誰かの所有物ですね。持ち主を特定すれば手がかりになります。', behavior: 'calm' },
        diary_entry: { reaction: '黒崎様の日記…これは重要な証拠になります。内容次第では。', behavior: 'calm' },
      },
    },
    {
      id: 'sonoda_yukino',
      name: '園田雪乃',
      appearance_id: 'female_young_alt',
      age: 24,
      occupation: '家政婦',
      description: '小柄で物静かな女性。館で長年働いており、館の事情を最もよく知っている。',
      personality: '観察眼が鋭い。普段は目立たないが、見ている。',
      alibi: 'キッチンで後片付けをしていたと主張。',
      secret: '白石が夜中に庭に出るのを目撃していた。',
      relationship_to_victim: '長年仕える家政婦。館の全てを知り尽くしている。',
      investigation_dialog: {
        greeting: '…何かお手伝いできることがあれば。私は目立たない存在ですが、見ています。',
        statements: [
          '昨晩、白石様が深夜に裏口から庭へ出るのを見ました。かなり長い時間外にいらっしゃいました。',
          '庭にはトリカブトが生えています。旦那様は何度か刈り取るよう言っていましたが、なかなか。',
          'キッチンに見知らぬ小瓶がありました。翌朝には消えていましたが。',
        ],
      },
      evidence_reactions: {
        poison_bottle: { reaction: 'これです！キッチンで見た小瓶に似ています。白石様が持っていかれた…。', behavior: 'nervous' },
        will_document: { reaction: '遺言書…旦那様は先月こっそり書き直されていました。白石様には内緒で、と言っていました。', behavior: 'sad' },
        herb_fragment: { reaction: 'これは庭のトリカブトですね。白石様が立っていた場所の近くに生えているもの。', behavior: 'nervous' },
        wine_glass: { reaction: 'そのグラス…白石様が旦那様のそばに立っていた時に持っていたものかも。', behavior: 'nervous' },
        muddy_shoes: { reaction: 'この泥の形…裏庭の土と同じです。深夜に出た方のものでしょう。', behavior: 'calm' },
        note_paper: { reaction: '白石様のお部屋で見たものと同じ紙に見えます。', behavior: 'nervous' },
        torn_letter: { reaction: '破られた手紙…ゴミ箱から回収したものかもしれません。', behavior: 'calm' },
        kitchen_knife: { reaction: 'これはキッチンの包丁です。普通のものですよ。', behavior: 'calm' },
        photo_garden: { reaction: 'この写真！これは白石様です。深夜の庭で何かを採っています。', behavior: 'nervous' },
        safe_key: { reaction: '旦那様の金庫の鍵…これは書斎にあったはずです。誰かが持ち出した？', behavior: 'nervous' },
        handkerchief: { reaction: 'これは白石様のハンカチです。イニシャルが刺繍してあります。', behavior: 'calm' },
        diary_entry: { reaction: '旦那様の日記。最後のページに白石様のことが書かれていたはずです。', behavior: 'sad' },
      },
    },
  ],
  rooms: [
    {
      id: 'room_study',
      name: '書斎',
      type_id: 'study',
      description: '重厚な木製の本棚に囲まれた部屋。主人の遺体が発見された場所。デスクの上には書類が散乱している。',
      evidence_ids: ['will_document', 'safe_key', 'diary_entry'],
    },
    {
      id: 'room_dining',
      name: 'ダイニング',
      type_id: 'dining_room',
      description: '長い晩餐テーブルが中央に置かれた部屋。昨晩の食器がまだ片付けられていない。',
      evidence_ids: ['wine_glass', 'handkerchief'],
    },
    {
      id: 'room_kitchen',
      name: 'キッチン',
      type_id: 'kitchen',
      description: '業務用の厨房設備が並ぶ広いキッチン。料理道具の隙間に何かが隠れているかもしれない。',
      evidence_ids: ['poison_bottle', 'kitchen_knife', 'note_paper'],
    },
    {
      id: 'room_library',
      name: '図書室',
      type_id: 'library',
      description: '古い書物が天井まで並ぶ図書室。医学書や植物図鑑なども混じっている。',
      evidence_ids: ['torn_letter'],
    },
    {
      id: 'room_garden',
      name: '庭園',
      type_id: 'garden',
      description: '洋館を囲む広大な庭園。様々な植物が植えられており、夜露に濡れた泥が足跡を残している。',
      evidence_ids: ['herb_fragment', 'muddy_shoes', 'photo_garden'],
    },
  ],
  evidence: [
    {
      id: 'poison_bottle',
      name: '小さな小瓶',
      category_id: 'poison',
      description: 'キッチンの棚の奥に隠されていた無色の液体が入った小瓶。微量でも致死量のアコニチンが含まれている。',
      is_fake: false,
      relevance: '犯行に使用された毒薬。白石誠の指紋が検出された。',
    },
    {
      id: 'will_document',
      name: '遺言書の写し',
      category_id: 'document_contract',
      description: '書斎の金庫に保管されていた遺言書のコピー。先月日付が変更されており、白石誠への相続分が削除されている。',
      is_fake: false,
      relevance: '白石誠の殺害動機を示す直接的な証拠。',
    },
    {
      id: 'herb_fragment',
      name: 'トリカブトの葉片',
      category_id: 'poison',
      description: '庭園で採取されたと思われるトリカブトの葉の断片。摘み取られた形跡がある。',
      is_fake: false,
      relevance: '毒の原料となった植物。採取場所の特定につながる。',
    },
    {
      id: 'wine_glass',
      name: '主人のワイングラス',
      category_id: 'container',
      description: 'ダイニングに残された被害者のワイングラス。底部に毒物の残留反応がある。',
      is_fake: false,
      relevance: '毒が投与された経路。グラスに近づいた人物が犯人の可能性が高い。',
    },
    {
      id: 'muddy_shoes',
      name: '泥のついた革靴',
      category_id: 'clothing',
      description: '庭園の特有の粘土質の土がついた革靴。サイズは26.5cm程度。',
      is_fake: false,
      relevance: '昨晩深夜に庭に出た人物のもの。白石誠のサイズと一致。',
    },
    {
      id: 'note_paper',
      name: '計算メモ',
      category_id: 'document_letter',
      description: 'キッチンで見つかった小さなメモ。アコニチンの致死量計算と思われる数式が走り書きされている。',
      is_fake: false,
      relevance: '事前に毒の量を計算していた証拠。筆跡鑑定で白石誠のものと判明。',
    },
    {
      id: 'safe_key',
      name: '金庫の鍵',
      category_id: 'key',
      description: '書斎の金庫を開ける鍵。通常は黒崎が肌身離さず持っていたはずだが、デスクの引き出しに放置されていた。',
      is_fake: false,
      relevance: '白石誠が金庫を開け遺言書を確認した証拠となりうる。',
    },
    {
      id: 'diary_entry',
      name: '日記の最終ページ',
      category_id: 'document_diary',
      description: '黒崎の日記。「白石には知らせていない。今夜の反応が見ものだ」という記述がある。',
      is_fake: false,
      relevance: '黒崎が遺言書変更を白石に意図的に隠していたことを示す。',
    },
    {
      id: 'photo_garden',
      name: '防犯カメラの画像',
      category_id: 'photograph',
      description: '庭園の防犯カメラが捉えた深夜の人物。トリカブトが生える区画に立っている。顔は不鮮明だが体型が白石誠に似る。',
      is_fake: false,
      relevance: '白石誠が深夜に庭でトリカブトを採取した可能性を示す写真証拠。',
    },
    {
      id: 'handkerchief',
      name: 'イニシャル入りハンカチ',
      category_id: 'fabric',
      description: 'ダイニングのテーブル下に落ちていた白いハンカチ。「S.M.」の刺繍がある。',
      is_fake: false,
      relevance: 'Shiraishi Makoto（白石誠）のイニシャルと一致。犯行現場付近に残された物証。',
    },
    {
      id: 'torn_letter',
      name: '破られた手紙の断片',
      category_id: 'document_letter',
      description: '図書室のゴミ箱から回収した手紙の断片。「…取引の証拠は私が握っている。おとなしくしていろ…」という文字が読める。',
      is_fake: true,
      relevance: '鬼頭武雄への脅迫状の可能性がある。ただし今回の殺人との直接的な関係はない偽の手がかり。',
    },
    {
      id: 'kitchen_knife',
      name: '血のついた包丁',
      category_id: 'weapon_blade',
      description: 'キッチンで発見された包丁。赤い染みがついているが、分析すると牛肉の血液と判明した。',
      is_fake: true,
      relevance: '一見すると凶器に見えるが、実際は料理で使用された無関係な包丁。',
    },
  ],
}
